### ISSUE TITLE
change `symbol$check` to `symbol$tick` in documentation

### ISSUE THREAD

**Issue by cjyetman** [r-lib/clisymbols#8]
`symbol$check` was changed to `symbol$tick` here https://github.com/r-lib/clisymbols/commit/fb1cae73eb65ddde3f26adf8e172f3c84c06a7f6

but it was not changed in the documentation...
https://github.com/r-lib/clisymbols/blob/03ca8240c6c912f50d0d31534c3148718fe5ec9a/R/symbols.R#L17

**Comment by gaborcsardi** [comment]
Thanks! Would you like to submit a PR?

**Comment by cjyetman** [comment]
I was going to, but since it's using an older/different version of Roxygen, rebuilding the docs caused all kinds of changes, and I thought it best to not manually edit or cherry-pick changes.
